### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'session'

### ISSUE THREAD

**Issue by bluesky632** [BigHeartC/Al_challenger_2018_sentiment_analysis#5]
Traceback (most recent call last):
  File "E:/kyl/2018.12.24/AI2018-17/code/train.py", line 295, in <module>
    train_GCAE()
  File "E:/kyl/2018.12.24/AI2018-17/code/train.py", line 230, in train_GCAE
    model_suffix=model_name)
  File "E:\kyl\2018.12.24\AI2018-17\code\GCAE_word_char.py", line 299, in run
    item in train_data])
  File "E:\kyl\2018.12.24\AI2018-17\code\GCAE_word_char.py", line 251, in train
    self.batch_size, True, self.dropout_keep):
  File "E:\kyl\2018.12.24\AI2018-17\code\GCAE_word_char.py", line 327, in get_batch_data
    for index in tqdm_notebook(get_batch_index(len(aspects), batch_size, is_shuffle), total=total):
  File "D:\Anaconda3\lib\site-packages\tqdm\__init__.py", line 25, in tqdm_notebook
    return _tqdm_notebook(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tqdm\_tqdm_notebook.py", line 212, in __init__
    self.fp, self.total, self.desc, self.ncols)
  File "D:\Anaconda3\lib\site-packages\tqdm\_tqdm_notebook.py", line 122, in status_printer
    container = HBox(children=[pbar, ptext])
  File "D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget_box.py", line 93, in HBox
    box.layout.display = 'flex'
  File "D:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 583, in __set__
    self.set(obj, value)
  File "D:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 572, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "D:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 1137, in _notify_trait
    type='change',
  File "D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 367, in notify_change
    self.send_state(key=name)
  File "D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 263, in send_state
    self._send(msg, buffers=buffers)
  File "D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 487, in _send
    self.comm.send(data=msg, buffers=buffers)
  File "D:\Anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 121, in send
    data=data, metadata=metadata, buffers=buffers,
  File "D:\Anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 66, in _publish_msg
    self.kernel.session.send(self.kernel.iopub_socket, msg_type,
AttributeError: 'NoneType' object has no attribute 'session'

**Comment by bluesky632** [comment]
您好，我是在windows下面运行的，请问一下你的keras和tensorflow的版本是多少

**Comment by mushengwang** [comment]
我是Ubuntu环境跟你遇到一样的问题，直接用pip把ipywidgets重装了问题就解决了
